#Ruta de pruebas
index:
   path: /inicio
   controller: App\Controller\HomeController::index


#Ruta de pruebas
animales:
   path: /animales
   controller: App\Controller\HomeController::animales

#Aqui vamos a listar todos los animales de la base de datos   
animal_index:
   path: /animal/index
   controller: App\Controller\AnimalController::index

#Ruta para guardar un animal
animal_save:
   path: /animal/save
   controller: App\Controller\AnimalController::save  

#Ruta para mostrar un animal en especifico
animal_detail:
   path: /animal/show/{id}
   controller: App\Controller\AnimalController::show

#Ruta para actualizar un animal   
animal_update:
   path: /animal/update/{id}
   controller: App\Controller\AnimalController::update

#Ruta para eliminar un animal en especifico
animal_delete:
   path: /animal/delete/{id}
   controller: App\Controller\AnimalController::delete

#Ruta para crear un nuevo animal
animal_create:
   path: /animal/crear
   controller: App\Controller\AnimalController::crear_animal


#Ruta para recibir datos del formulario y crear nuevo animal
animal_guardar:
   path: /animal/guardar
   controller: App\Controller\AnimalController::guardar_animal
   methods: [POST]

   

   
